keycloak:
  extraVolumes:
    - name: themes-catenax-shared
      emptyDir: {}
    - name: themes-catenax-shared-portal
      emptyDir: {}
    - name: realms
      emptyDir: {}
    - name: realm-secrets
      secret:
        secretName: secret-sharedidp-realms
  extraVolumeMounts:
    - name: themes-catenax-shared
      mountPath: "/opt/bitnami/keycloak/themes/catenax-shared"
    - name: themes-catenax-shared-portal
      mountPath: "/opt/bitnami/keycloak/themes/catenax-shared-portal"
    - name: realms
      mountPath: "/realms"
    - name: realm-secrets
      mountPath: "/secrets"
  initContainers:
    - name: import
      image: ftcpro.azurecr.io/keycloak/product-portal-iam_iam-import-dev-new-cf:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes-catenax-shared..."
          cp -R /import/themes/catenax-shared/* /themes-catenax-shared
          echo "Copying themes-catenax-shared-portal..."
          cp -R /import/themes/catenax-shared-portal/* /themes-catenax-shared-portal
          echo "Copying realms..."
          cp -R /import/catenax-shared/realms/* /realms
          echo "Copying realms-secrets..."
          cp /secrets/* /realms
      volumeMounts:
      - name: themes-catenax-shared
        mountPath: "/themes-catenax-shared"
      - name: themes-catenax-shared-portal
        mountPath: "/themes-catenax-shared-portal"
      - name: realms
        mountPath: "/realms"
      - name: realm-secrets
        mountPath: "/secrets"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: sharedidp.dev.ftcpro.co
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
      nginx.ingress.kubernetes.io/cors-allow-origin: https://portal.dev.ftcpro.co
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
  externalDatabase:
    host: "postgresql-primary.postgres"
    port: 5432
    user: "sharedidp"
    database: "iamsharedidp"
    existingSecret: sharedidp-postgres
    secret:
      path: portal/data/dev/iam/sharedidp-postgres
  extraEnvVars:
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sharedidp-keycloak
          key: admin-password
    - name: KEYCLOAK_DATABASE_HOST
      value: postgresql-primary.postgres
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realms -Dkeycloak.migration.strategy=IGNORE_EXISTING"
  replicaCount: 1
  postgresql:
    enabled: false
    architecture: "standalone"
    
secrets:
  auth:
    existingSecret:
      adminpassword: "<path:portal/data/dev/iam/sharedidp-keycloak#admin-password>"
      managementpassword: "<path:portal/data/dev/iam/sharedidp-keycloak#management-password>"
  postgresql:
    auth:
      existingSecret:
        postgrespassword: "<path:portal/data/dev/iam/sharedidp-postgres#postgres-password>"
        password: "<path:portal/data/dev/iam/sharedidp-postgres#password>"
        replicationPassword: "<path:portal/data/dev/iam/sharedidp-postgres#replication-password>"
  realmuser:
    enabled: true
    cxtestaccessuser: "<path:portal/data/iam/sharedidp-user#CX-Test-Access-users-0.json>"
    company1user: "<path:portal/data/iam/sharedidp-user#Company-1-users-0.json>"
    company2user: "<path:portal/data/iam/sharedidp-user#Company-2-users-0.json>"
    securitycompany: "<path:portal/data/iam/sharedidp-user#Security-Company-users-0.json>"
    serviceprovider: "<path:portal/data/iam/sharedidp-user#idp4-users-0.json>"
    appprovider: "<path:portal/data/iam/sharedidp-user#idp5-users-0.json>"
    cxoperator: "<path:portal/data/iam/sharedidp-user#idp6-users-0.json>"
