FROM alpine:3.16

RUN mkdir import

RUN chown -R 1000:3000 /import
USER 1000:3000

COPY import/keycloak-themes/ import/themes
COPY import/realm-config/generic/catenax-central/ import/catenax-central/realms
COPY import/realm-config/generic/catenax-shared/ import/catenax-shared/realms
