FROM alpine:3.16

RUN mkdir import

RUN chown -R 1000:3000 /import
USER 1000:3000

COPY import/keycloak-themes/ import/themes
COPY import/realm-config/consortia/catenax-central/beta/ import/catenax-central/realms
COPY import/realm-config/consortia/catenax-shared/master/beta/ import/catenax-shared/realms
COPY import/realm-config/consortia/catenax-shared/test-realms/ import/catenax-shared/realms
