keycloak:
  replicaCount: 1
  extraVolumes:
    - name: themes
      emptyDir: {}
    - name: realms
      emptyDir: {}
  extraVolumeMounts:
    - name: themes
      mountPath: "/opt/bitnami/keycloak/themes/catenax-central"
    - name: realms
      mountPath: "/realms"
  initContainers:
    - name: import
      image: ftcpro.azurecr.io/keycloak/product-portal-iam_iam-import-dev-new-cf:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /import/themes/catenax-central/* /themes
          echo "Copying realms..."
          cp -R /import/catenax-central/realms/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: centralidp.dev.ftcpro.co
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
      nginx.ingress.kubernetes.io/cors-allow-origin: https://portal.dev.ftcpro.co, https://partners-pool.dev.ftcpro.co
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true
  postgresql:
    enabled: false
    architecture: "standalone"

  externalDatabase:
    host: "postgresql-primary.postgres"
    port: 5432
    user: "cerntralidp"
    database: "iamcentralidp"
    existingSecret: centralidp-postgres
    secret:
      path: portal/data/dev/iam/centralidp-postgres

  extraEnvVars:
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: centralidp-keycloak
          key: admin-password
    - name: KEYCLOAK_DATABASE_HOST
      value: postgresql-primary.postgres

secrets:
  auth:
    existingSecret:
      adminpassword: "<path:portal/data/dev/iam/centralidp-keycloak#admin-password>"
      managementpassword: "<path:portal/data/dev/iam/centralidp-keycloak#management-password>"
  postgresql:
    auth:
      existingSecret:
        postgrespassword: "<path:portal/data/dev/iam/centralidp-postgres#postgres-password>"
        password: "<path:portal/data/dev/iam/centralidp-postgres#password>"
        replicationPassword: "<path:portal/data/dev/iam/centralidp-postgres#replication-password>"

