keycloak:
  image:
    tag: 16.1.1-debian-10-r103
  auth:
    adminUser: admin
    existingSecret: centralidp-keycloak
  proxyAddressForwarding: true
  serviceDiscovery:
    enabled: true
  extraEnvVars:
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: centralidp-keycloak
          key: admin-password
    - name: CACHE_OWNERS_COUNT
      value: "3"
    - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
      value: "3"
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realms -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    - name: KEYCLOAK_DATABASE_HOST
      value: ftcpro-postgresql-primary.postgres
  replicaCount: 1
  extraVolumes:
    - name: themes
      emptyDir: {}
    - name: realms
      emptyDir: {}
  extraVolumeMounts:
    - name: themes
      mountPath: "/opt/bitnami/keycloak/themes/catenax-central"
    - name: realms
      mountPath: "/realms"
  initContainers:
    - name: import
      image: ftcpro.azurecr.io/keycloak/product-portal-iam_iam-import-dev:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /import/themes/catenax-central/* /themes
          echo "Copying realms..."
          cp -R /import/catenax-central/realms/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
  service:
    type: ClusterIP
    sessionAffinity: ClientIP
  ingress:
    enabled: false
  rbac:
    create: true
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
  postgresql:
    enabled: false
    # auth:
    #   username: kccentral
    #   database: iamcentralidp
    #   existingSecret: centralidp-postgres
    # architecture: replication
  externalDatabase:
    host: "ftcpro-postgresql-primary.postgres"
    port: 5432
    user: "postgres"
    database: "iamcentralidp"
    existingSecret: centralidp-postgres
    secret:
      path: portal/data/dev/iam/centralidp-postgres


secrets:
  auth:
    existingSecret:
      adminpassword: "<path:portal/data/dev/iam/centralidp-keycloak#admin-password>"
      managementpassword: "<path:portal/data/dev/iam/centralidp-keycloak#management-password>"
  postgresql:
    auth:
      existingSecret:
        postgrespassword: "<path:portal/data/dev/iam/centralidp-postgres#postgres-password>"
        password: "<path:portal/data/dev/iam/centralidp-postgres#password>"
        replicationPassword: "<path:portal/data/dev/iam/centralidp-postgres#replication-password>"
  realmuser:
    enabled: false
    cxcentraluser: "<path:portal/data/dev/iam/centralidp-realms#CX-Central-users-0.json>"


