###############################################################
# Copyright (c) 2021,2022 Contributors to the CatenaX (ng) GitHub Organisation.
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

keycloak:
  image:
    tag: 16.1.1-debian-10-r103
  auth:
    adminUser: admin
    existingSecret: centralidp-keycloak
  proxyAddressForwarding: true
  serviceDiscovery:
    enabled: true
  extraEnvVars:
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          name: centralidp-keycloak
          key: admin-password
    - name: CACHE_OWNERS_COUNT
      value: "3"
    - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
      value: "3"
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realms -Dkeycloak.migration.strategy=IGNORE_EXISTING"
  replicaCount: 3
  extraVolumes:
    - name: themes
      emptyDir: {}
    - name: realms
      emptyDir: {}
  extraVolumeMounts:
    - name: themes
      mountPath: "/opt/bitnami/keycloak/themes/catenax-central"
    - name: realms
      mountPath: "/realms"
  initContainers:
    - name: import
      image: ghcr.io/catenax-ng/product-portal-iam_iam-import:v0.6.0
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /import/themes/catenax-central/* /themes
          echo "Copying realms..."
          cp -R /import/catenax-central/realms/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
  service:
    type: ClusterIP
    sessionAffinity: ClientIP
  ingress:
    enabled: false
  rbac:
    create: true
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
  postgresql:
    enabled: true
    auth:
      username: kccentral
      database: iamcentralidp
      existingSecret: centralidp-postgres
    architecture: replication

secrets:
  auth:
    existingSecret:
      adminpassword: ""
      managementpassword: ""
  postgresql:
    auth:
      existingSecret:
        postgrespassword: ""
        password: ""
        replicationPassword: ""
