keycloak:
  extraVolumes:
    - name: themes
      emptyDir: {}
    - name: realms
      emptyDir: {}
    - name: realm-secrets
      secret:
        secretName: secret-centralidp-realms
  extraVolumeMounts:
    - name: themes
      mountPath: "/opt/bitnami/keycloak/themes/catenax-central"
    - name: realms
      mountPath: "/realms"
    - name: realm-secrets
      mountPath: "/secrets"
  initContainers:
    - name: import
      image: ftcpro.azurecr.io/keycloak/product-portal-iam_iam-import-dev:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /import/themes/catenax-central/* /themes
          echo "Copying realms..."
          cp -R /import/catenax-central/realms/* /realms
          # echo "Copying realms-secrets..."
          # cp /secrets/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
      - name: realm-secrets
        mountPath: "/secrets"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: centralidp.dev.demo.ftcpro.co
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
      nginx.ingress.kubernetes.io/cors-allow-origin: https://portal.dev.demo.ftcpro.co
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true

secrets:
  auth:
    existingSecret:
      adminpassword: "<path:portal/data/dev/iam/centralidp-keycloak#admin-password>"
      managementpassword: "<path:portal/data/dev/iam/centralidp-keycloak#management-password>"
  postgresql:
    auth:
      existingSecret:
        postgrespassword: "<path:portal/data/dev/iam/centralidp-postgres#postgres-password>"
        password: "<path:portal/data/dev/iam/centralidp-postgres#password>"
        replicationPassword: "<path:portal/data/dev/iam/centralidp-postgres#replication-password>"
  realmuser:
    enabled: true
    cxcentraluser: "<path:portal/data/dev/iam/centralidp-realms#CX-Central-users-0.json>"
